title: Eduardo Batista # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer.<br><br>
  Master's graduate in Technological Physics Engineering at Instituto Superior Técnico.<br><br>
  Data science enthusiast with interest in deep learning, physics and modelling.
  <br><br>
  <a href="https://www.linkedin.com/in/eduardojfbatista/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
